services:
  - type: web
    name: tasky-web
    buildCommand: mvn package
    envVars:
      - key: DB_USER
        value: finalprojectoop2025database_user
      - key: DB_PASSWORD
      - key: DB_URL
        value: jdbc:postgresql://<host>.render.com:5432/finalprojectoop2025database